// Generated by CoffeeScript 1.3.3
(function() {

  describe('Array', function() {
    return describe('#indexOf()', function() {
      return it('should return -1 when the value is not present', function() {
        expect([1, 2, 3].indexOf(5)).toEqual(-1);
        return expect([1, 2, 3].indexOf(0)).toEqual(-1);
      });
    });
  });

}).call(this);
